### ISSUE TITLE
Pydeck + Earth Engine: Terrain Visualization Not visualize in colab

### ISSUE THREAD

**Issue by BijoyKrGayen** [UnfoldedInc/earthengine-layers#115]
Hi I have tried to run the example [Pydeck + Earth Engine: Terrain Visualization notebook](https://github.com/UnfoldedInc/earthengine-layers/blob/master/py/examples/terrain.ipynb) command in colab. But at the end, it doesn't show any map in colab.
![3d](https://user-images.githubusercontent.com/43729047/121841560-318bc300-ccfc-11eb-8c31-7c4f36e61582.jpg)

**Comment by kylebarron** [comment]
Colab does not support Jupyter Widgets. You should try [`.to_html`](https://pydeck.gl/deck.html?highlight=colab#pydeck.bindings.deck.Deck.to_html) which supports Colab, however I'm not 100% sure the Earth Engine integration also supports `.to_html` because of how authentication support works with Earth Engine. I would expect it to work until the token expires, which is usually within one hour.

**Comment by BijoyKrGayen** [comment]
Thanks @kylebarron It works now by setting .to_html.

**Comment by kylebarron** [comment]
Good to hear!
