### ISSUE TITLE
Consider shortening the package name?

### ISSUE THREAD

**Issue by giswqs** [UnfoldedInc/earthengine-layers#29]
The pypi package name `pydeck-earthengine-layers` is a bit lengthy. Have you consider shortening the name, e.g., pydeck-ee-layers, pydeck-gee? Users will appreciate shorter names when installing the package.

**Comment by ibgreen** [comment]
@giswqs Thanks for the suggestion!

We kind of chuckled when you raised this question because we actually did discuss this, and this was our take:

- The argument for shortening it is that python users typically like to use abbreviations and short pretty names, so it would be nice to follow that approach

The case against shortening it is that: 
- this module will be available in several languages, at least JS and python for now, and there will be other layer extension modules for deck.gl
- and we like to have consistent naming across languages and modules
- and we don't want to shorten the name in other languages because our conventions there are to always type things out for clarity.

**Comment by ibgreen** [comment]
Keeping this open until we do our API audit before official release.

**Comment by giswqs** [comment]
Thank you for the clarification. This makes a lot of sense. Consistency across different languages is certainly more important than convenience just in Python.
