### ISSUE TITLE
Animation Example

### ISSUE THREAD

**Issue by ibgreen** [UnfoldedInc/earthengine-layers#39]
Goal is to demonstrate and improve support for animation using pydeck.

Perhaps make an example using ImageCollection.

**Comment by giswqs** [comment]
Here are two animation examples I have done with [geemap](https://github.com/giswqs/geemap). It would be nice if pydeck can do sth similar. 

1. Adding colorbar and images to GIF animations generated from Earth Engine data ([video](https://youtu.be/CpT3LQPNKJs) | [gif](https://i.imgur.com/13tFMSI.gif) | [notebook](https://github.com/giswqs/geemap/blob/master/examples/notebooks/17_add_colorbar_to_gif.ipynb))
2. Creating Landsat timelapse animations with animated text using Earth Engine ([video](https://youtu.be/OwjSJnGWKJs) | [gif](https://i.imgur.com/XOHOeXk.gif) | [notebook](https://github.com/giswqs/geemap/blob/master/examples/notebooks/18_create_landsat_timelapse.ipynb))

![](https://i.imgur.com/13tFMSI.gif)
![](https://i.imgur.com/IQUJrkW.gif)

**Comment by ibgreen** [comment]
@giswqs - Thanks, this looks awesome! We will take a look and try to make sure can match this with pydeck.

**Comment by kylebarron** [comment]
There are a couple different possibilities here, depending on whether the animation is generated server-side with Earth Engine, or locally by stepping through a collection of individual `ee.Image`s.

### Server-side animation

I think both of @giswqs 's examples are generated server-side? From the notebooks it _looks_ like there isn't local image processing combining individual image frames, though with the Landsat example it's possible local image processing is hidden within `geemap.Map.add_landsat_ts_gif`.

From the [EE docs](https://developers.google.com/earth-engine/ic_visualization#video_thumb), it looks like the standard way to create an animation from an `ImageCollection` is to use `ee.ImageCollection.getVideoThumbURL()`. This generates a gif from the `ImageCollection` on Earth Engine's servers.

But the docs indicate:
> The maximum number of pixels allowed in an animation is 6,553,600 (e.g., 256 x 256 x 100)

So it isn't feasible to create a single animation at global scale, unless it's very low resolution.

A possible workaround with this approach is to create a _`TileLayer`_ of animations. I believe the `BitmapLayer` can handle an animated `gif`, so it would be possible to create a separate `256x256` animation for each mercator tile, and then work to make sure each gif animation is in sync with the others.

### Client-side animation

Since deck.gl is powerful, rendering the animation client-side is clearly of interest. There are a couple considerations with this:

**Tile url isn't unique per set of `Image * visParams`**. Currently we deep compare `visParams` to prevent requesting a new map url if the `visParams` haven't changed since the previous props, but if we have an animation using a single `EarthEngineLayer` where the `Image` or `visParams` rotate through a series of 30 frames, the 1st and 31st frame will represent the same dataset but will generate a new map url, and thus no caching will happen.

**Rotate visibility prop of many layers.** Another possibility is to have 30 _separate `EarthEngineLayer`s_, where in each animation frame the `visibility` prop is set to false on the active layer and `true` on the next active layer. This prevents requesting a new map url for layers whose `ee.Image` and `visParams` props don't change, and should thus allow better caching. But this means that the user must handle a few dozen layers and when to enable visibility. Or we'd have to handle that case inside the _EarthEngineLayer_ by rendering the number of frames as separate `subLayer` `EarthEngineLayer`s.

Regardless, there could be some lag initially while loading since the tiles requested change each frame, and it might take a few seconds to cache all the results.

**Comment by giswqs** [comment]
@kylebarron In geemap, the animations are generated on the server-side using `ee.ImageCollection.getVideoThumbURL()` and downloaded automatically as a GIF to local drive. Animated text, label, and progress bar are added locally using the `pillow` package as GEE server-side could not do this. Here are some relevant functions in geemap : 
- [download_ee_video()](https://github.com/giswqs/geemap/blob/master/geemap/geemap.py#L2663)
- [add_text_to_gif()](https://github.com/giswqs/geemap/blob/master/geemap/geemap.py#L2663)
- [add_image_to_gif()](https://github.com/giswqs/geemap/blob/master/geemap/geemap.py#L2663)

**Comment by kylebarron** [comment]
That makes sense. We might be able to have animated text, labels, and progress bars on the JavaScript side inside deck.gl, but first it's more important to have a working interactive animation.

**Comment by ibgreen** [comment]
For our purposes, we probably want to focus on supporting animation of ImageCollections with a reasonable amount of Images (<100(.

We could add `time` prop and `timeRange` props to the EELayer.
- Setting `time` would select which Image in the ImageCollection we show.

Ddownload filmstrip tiles for ee.ImageCollection:
- Fetch FilmStrips for ImageCollection.
- Need to be split client side 256x256x100 
- 40 images in 10s. 10s of seconds to first byte...

We'd need to manage the cutting in the `EElayer`, and we'd need to update the bitmap layers when the `time` prop advances.

**Comment by kylebarron** [comment]
For reference, the example of a filmstrip in the EE docs is such:

![](https://developers.google.com/earth-engine/images/ImageCollection_filmstrip_transparent_bg.png)

From the following code:
```js
// Define an area of interest geometry with a global non-polar extent.
var aoi = ee.Geometry.Polygon(
  [[[-179.0, 78.0], [-179.0, -58.0], [179.0, -58.0], [179.0, 78.0]]], null,
  false);

// Import hourly predicted temperature image collection for northern winter
// solstice. Note that predictions extend for 384 hours; limit the collection
// to the first 24 hours.
var tempCol = ee.ImageCollection('NOAA/GFS0P25')
  .filterDate('2018-12-22', '2018-12-23')
  .limit(24)
  .select('temperature_2m_above_ground');

// Define arguments for the getFilmstripThumbURL function parameters.
var filmArgs = {
  dimensions: 128,
  region: aoi,
  crs: 'EPSG:3857',
  min: -40.0,
  max: 35.0,
  palette: ['blue', 'purple', 'cyan', 'green', 'yellow', 'red']
};

// Print a URL that will produce the filmstrip when accessed.
print(tempCol.getFilmstripThumbURL(filmArgs));
```

So to use the filmstrip as the animation medium we'd have to:
- create a polygon with each mercator tile bounds
- call `getFilmstripThumbURL` on the `ImageCollection`
- Figure out which `xy` image coordinates to select for each frame given the number of coordinates. I'd prefer to call the prop `frame` rather than `time`, which might be easily confused with the timestamp of the actual images, while an `ImageCollection` doesn't need to track with actual image time.
- Create a custom bitmap layer to render that small portion of the image.

Other considerations:
- Region: Unlike the static map, new tiles wouldn't automatically load as you pan. We'd have to call `getFilmstripThumbURL` on tiles newly in the viewport
- Strip number: Is there always the number of the strip in the top left of each image?

**Comment by ibgreen** [comment]
Also see: https://earthengine.google.com/timelapse/ - an example of pregenerated video tiles. We could display this, but synchronizing them would require work, and it is just one dataset.

**Comment by kylebarron** [comment]
Animation supported as of #54, I'll include examples in the repository soon.
